@startuml

header Демо проект
title Диаграмма компонентов

rectangle "Interfaces (Primary Adapters)" {
  [Shop API] as shop_api
  [Alembic (migrations)] as alembic
  [Rabbitmq consumer] as rabbitmq_consumer
}

rectangle "Application" {
  [Shop] as shop
  interface "Shop repositories" as shop_repositories
  interface "Shop publisher" as shop_publisher
  interface "Shop mail sender" as shop_mail_sender
}

rectangle "Adapters (Secondary Adapters)" {
  [Database] as database
  [Publisher] as publisher
  [Mail sender] as mail_sender
}

() "AMQP" as amqp
() "HTTP API" as http_api

rabbitmq_consumer -u-( amqp
shop_api -u-( http_api
shop_api ..> shop
rabbitmq_consumer ..> shop

shop --( shop_repositories
shop --( shop_publisher
shop --( shop_mail_sender

mail_sender -u- shop_mail_sender
publisher -u- shop_publisher
database -u- shop_repositories
database -u- alembic

@enduml