openapi: 3.0.3
info:
  title: demo project
  version: 0.0.1

servers:
  - url: http://127.0.0.1:8000
    description: Сервер для локальной разработки


paths:
  /api/catalog/show_product:
    get:
      summary: Возвращает информацию о товаре
      parameters:
        - in: query
          name: sku
          schema:
            type: string
          required: true
          example: 'U-001'
      responses:
        '200':
          description: JSON объект с данными о товаре
          content:
            application/json:
              schema:
                type: object
                required:
                  - sku
                  - title
                  - description
                  - price
                properties:
                  sku:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  price:
                    type: number
                    format: float
              example:
                sku: 'U-001'
                title: 'Дрель'
                description: 'Дрель с функцией перфоратора'
                price: 4534.22
        '400':
          description: Ошибка запроса
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: 'errors.yaml#/validationError'
                  - $ref: 'errors.yaml#/appError'

  /api/catalog/search_products:
    get:
      summary: Поиск по названию или описанию
      parameters:
        - in: query
          name: search
          schema:
            type: string
          required: false
          example: 'О'
        - in: query
          name: limit
          schema:
            type: integer
            format: int32
          required: false
          default: 10
          example: 10
        - in: query
          name: offset
          schema:
            type: integer
            format: int32
          required: false
          default: 0
          example: 0
      responses:
        '200':
          description: JSON объект с данными о товарах
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - sku
                    - title
                    - description
                    - price
                  properties:
                    sku:
                      type: string
                    title:
                      type: string
                    description:
                      type: string
                    price:
                      type: number
                      format: float
              example:
                - sku: 'U-001'
                  title: 'Дрель'
                  description: 'Дрель с функцией перфоратора'
                  price: 4534.22
                - sku: 'U-002'
                  title: 'Отвертка'
                  description: 'Отвертка удлиненная крестовая'
                  price: 454.22
        '400':
          description: Ошибка запроса
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: 'errors.yaml#/validationError'
                  - $ref: 'errors.yaml#/appError'

  /api/checkout/show_cart:
    get:
      summary: Посмотреть содержимое корзины текущего пользователя
      responses:
        '200':
          description: JSON объект с данными о товарах в корзине
          content:
            application/json:
              schema:
                type: object
                required:
                  - positions
                properties:
                  positions:
                    type: array
                    items:
                      type: object
                      required:
                        - product_sku
                        - product_price
                        - quantity
                      properties:
                        sku:
                          type: string
                        product_price:
                          type: number
                          format: float
                        quantity:
                          type: integer
                          format: int32
              example:
                positions:
                  - product_sku: 'U-001'
                    product_price: 4534.22
                    quantity: 12
                  - product_sku: 'U-002'
                    product_price: 454.22
                    quantity: 2
        '400':
          description: Ошибка запроса
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: 'errors.yaml#/validationError'
                  - $ref: 'errors.yaml#/appError'

  /api/checkout/add_product_to_cart:
    post:
      summary: Добавляет товар в корзину для текущего пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - sku
              properties:
                sku:
                  type: string
                quantity:
                  type: integer
                  format: int32
                  minimum: 1
              example:
                  sku: 'U-001'
                  quantity: 1
      responses:
        '200':
          description: ОК
        '400':
          description: Ошибка запроса
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: 'errors.yaml#/validationError'
                  - $ref: 'errors.yaml#/appError'

  /api/checkout/remove_product_from_cart:
    post:
      summary: Удаляет товар из корзины для текущего пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - sku
              properties:
                sku:
                  type: string
              example:
                  sku: 'U-001'
      responses:
        '200':
          description: ОК
        '400':
          description: Ошибка запроса
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: 'errors.yaml#/validationError'
                  - $ref: 'errors.yaml#/appError'

  /api/checkout/register_order:
    post:
      summary: Создает новый заказ для текущего пользователя, товары берутся из корзины
      responses:
        '200':
          description: JSON объект с номером заказа
          content:
            application/json:
              schema:
                type: object
                required:
                  - order_number
                properties:
                  order_number:
                    type: integer
                    format: int32
              example:
                order_number: 1
                    
        '400':
          description: Ошибка запроса
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: 'errors.yaml#/validationError'
                  - $ref: 'errors.yaml#/appError'

  /api/orders/show_order:
    get:
      summary: Посмотреть содержимое заказа для текущего пользователя
      parameters:
        - in: query
          name: number
          schema:
            type: integer
            format: int32
          required: true
          example: 1
      responses:
        '200':
          description: JSON объект с данными о товарах в корзине
          content:
            application/json:
              schema:
                type: object
                required:
                  - number
                  - positions
                properties:
                  number:
                    type: integer
                    format: int32
                  positions:
                    type: array
                    items:
                      type: object
                      required:
                        - sku
                        - product_title
                        - quantity
                        - price
                      properties:
                        sku:
                          type: string
                        product_title:
                          type: string
                        quantity:
                          type: integer
                          format: int32
                        price:
                          type: number
                          format: float
              example:
                number: 1
                positions:
                  - sku: 'U-001'
                    product_title: 'Отвертка'
                    quantity: 12
                    price: 4534.22
                  - sku: 'U-002'
                    product_title: 'Дрель'
                    quantity: 2
                    price: 454.22
        '400':
          description: Ошибка запроса
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: 'errors.yaml#/validationError'
                  - $ref: 'errors.yaml#/appError'

  /api/customers/show_info:
    get:
      summary: Посмотреть информацию о покупателе (могут только админы)
      parameters:
        - in: query
          name: customer_id
          schema:
            type: integer
            format: int32
          required: true
          example: 2
      responses:
        '200':
          description: OK
        '400':
          description: Ошибка запроса
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: 'errors.yaml#/appError'
                  - $ref: 'errors.yaml#/validationError'
